// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCynwa1teXV1osAviqhsJejuLnXDLH4udE',
    appId: '1:1039976153966:web:f48dbf35c9ab5753b4b77f',
    messagingSenderId: '1039976153966',
    projectId: 'kztest-30cb8',
    authDomain: 'kztest-30cb8.firebaseapp.com',
    storageBucket: 'kztest-30cb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFyCQEWeCr3XLr2BS07vzcDCLZAhnhXdw',
    appId: '1:1039976153966:android:e301684f0c8a339fb4b77f',
    messagingSenderId: '1039976153966',
    projectId: 'kztest-30cb8',
    storageBucket: 'kztest-30cb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4b2dZN08kzLGJCNKCY37VcCIhCNZsbsM',
    appId: '1:1039976153966:ios:6150740b5181d837b4b77f',
    messagingSenderId: '1039976153966',
    projectId: 'kztest-30cb8',
    storageBucket: 'kztest-30cb8.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4b2dZN08kzLGJCNKCY37VcCIhCNZsbsM',
    appId: '1:1039976153966:ios:95bee8285888ccc8b4b77f',
    messagingSenderId: '1039976153966',
    projectId: 'kztest-30cb8',
    storageBucket: 'kztest-30cb8.appspot.com',
    iosBundleId: 'com.example.firstapp.RunnerTests',
  );
}
